package com.surenjanath.crownfoundry.engine

import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The export people take elsewhere.
 *
 * The round trip is the real test: if what this writes reads back as the same move list, and that
 * list still replays through the engine, then the file is well-formed rather than merely
 * plausible-looking.
 */
class PdnTest {

    private val moves = listOf(
        "11-16", "24-20", "8-11", "28-24", "9-14", "23-18", "14x23",
        "26x19", "16x23", "27x18", "10-15", "31-27", "4-8", "21-17"
    )

    @Test
    fun `the seven-tag roster comes first and is complete`() {
        val pdn = Pdn.export(moves, Pdn.Tags(date = "2026.08.17", result = Pdn.RESULT_BLACK))
        val tags = Pdn.tagsOf(pdn)

        assertEquals(
            listOf("Event", "Site", "Date", "Round", "White", "Black", "Result"),
            tags.keys.toList().take(7)
        )
        assertEquals("2026.08.17", tags["Date"])
        assertEquals(Pdn.RESULT_BLACK, tags["Result"])
    }

    @Test
    fun `black moves first, so move one holds two plies starting with black`() {
        // The opposite pairing to chess, and the thing most likely to be got wrong.
        val text = Pdn.movetext(moves, Pdn.RESULT_BLACK)
        assertTrue(text, text.startsWith("1. 11-16 24-20 2. 8-11 28-24 3."))
        assertTrue(text, text.trimEnd().endsWith(Pdn.RESULT_BLACK))
    }

    @Test
    fun `an odd number of plies still numbers correctly`() {
        val text = Pdn.movetext(listOf("11-15", "22-18", "15x22"))
        assertTrue(text, text.startsWith("1. 11-15 22-18 2. 15x22"))
    }

    @Test
    fun `moves survive a round trip and still replay`() {
        val pdn = Pdn.export(moves, Pdn.Tags(result = Pdn.RESULT_BLACK))
        val recovered = Pdn.movesOf(pdn)

        assertEquals(moves, recovered)
        // The strongest form of "well-formed": the engine accepts what came back.
        assertEquals(moves.size, replayMoves(recovered).size)
    }

    @Test
    fun `a long game wraps without losing or joining tokens`() {
        val long = List(60) { if (it % 2 == 0) "11-15" else "22-18" }
        val text = Pdn.movetext(long)

        assertTrue("lines ran past the wrap width", text.lines().all { it.length <= 79 })
        assertEquals(long.size, Pdn.movesOf(text).size)
    }

    @Test
    fun `results are written from white's side`() {
        // The human is Black here, so a game you won exports as 0-1. Worth pinning.
        assertEquals(Pdn.RESULT_BLACK, Pdn.resultOf(BLACK))
        assertEquals(Pdn.RESULT_WHITE, Pdn.resultOf(WHITE))
        assertEquals(Pdn.RESULT_DRAW, Pdn.resultOf(DRAW_RESULT))
        assertEquals(Pdn.RESULT_UNFINISHED, Pdn.resultOf(null))
    }

    @Test
    fun `english rules claim GameType 20 and anything else does not`() {
        val english = Pdn.tagsOf(Pdn.export(moves, Pdn.Tags(rules = VariantRules.ENGLISH)))
        assertEquals("20", english["GameType"])
        assertEquals(null, english["Variant"])

        // The app's default is flying kings with backward captures - not English draughts, and
        // labelling it GameType 20 would make the file wrong in a way a reader cannot detect.
        val flying = Pdn.tagsOf(Pdn.export(moves, Pdn.Tags(rules = VariantRules.DEFAULT)))
        assertEquals(null, flying["GameType"])
        assertNotNull(flying["Variant"])
        assertTrue(flying["Variant"]!!, flying["Variant"]!!.contains("flying kings"))
    }

    @Test
    fun `quotes in a tag value do not break the file`() {
        val pdn = Pdn.export(moves, Pdn.Tags(event = """A "friendly" game\match"""))
        assertEquals("""A "friendly" game\match""", Pdn.tagsOf(pdn)["Event"])
        assertEquals(moves, Pdn.movesOf(pdn))
    }

    @Test
    fun `comments, variations and glyphs are skipped rather than read as moves`() {
        val messy = """
            [Event "Untidy"]

            1. 11-15 {a solid opening} 22-18 ; trailing thought
            2. 15x22 $1 25x18 (2... 15-19 23x16) 3. 12-16 *
        """.trimIndent()

        assertEquals(listOf("11-15", "22-18", "15x22", "25x18", "12-16"), Pdn.movesOf(messy))
    }

    @Test
    fun `an empty game is still a valid document`() {
        val pdn = Pdn.export(emptyList())
        assertEquals(Pdn.RESULT_UNFINISHED, Pdn.tagsOf(pdn)["Result"])
        assertTrue(Pdn.movesOf(pdn).isEmpty())
    }

    @Test
    fun `a real played-out game exports and replays`() = runTest {
        // Generated by the engine so the fixture cannot drift out of date.
        var board = Board.initial()
        val played = ArrayList<String>()
        val random = kotlin.random.Random(5)
        repeat(40) {
            val legal = board.legalMoves()
            if (legal.isEmpty()) return@repeat
            val move = legal[random.nextInt(legal.size)]
            played.add(move.notation())
            board = board.apply(move)
        }

        val pdn = Pdn.export(played, Pdn.Tags(result = Pdn.resultOf(board.winner())))

        assertEquals(played, Pdn.movesOf(pdn))
        assertEquals(played.size, replayMoves(Pdn.movesOf(pdn)).size)
    }
}
