# Generated by Django 6.1 on 2026-08-16 16:12

import django.db.models.deletion
import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('elo_rating', models.IntegerField(default=1200)),
                ('style_aggression', models.FloatField(default=0.0)),
                ('style_king_rush', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard'), ('adaptive', 'adaptive')], default='adaptive', max_length=16)),
                ('status', models.CharField(choices=[('active', 'active'), ('finished', 'finished')], default='active', max_length=16)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, choices=[('black', 'black'), ('white', 'white'), ('draw', 'draw')], max_length=8, null=True)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('ai_captures', models.PositiveIntegerField(default=0)),
                ('human_captures', models.PositiveIntegerField(default=0)),
                ('board_fen', models.TextField(default=game.models.initial_fen)),
                ('plies_since_progress', models.PositiveIntegerField(default=0)),
                ('repetition_history', models.JSONField(blank=True, default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='game.playerprofile')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('board_fen', models.TextField()),
                ('current_player', models.CharField(max_length=8)),
                ('move_notation', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.match')),
            ],
            options={
                'ordering': ('turn_number',),
                'constraints': [models.UniqueConstraint(fields=('match', 'turn_number'), name='unique_turn_per_match')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['player', '-start_time'], name='game_match_player__28ab6b_idx'),
        ),
    ]
