# Generated by Django 6.1 on 2026-08-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rules_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
