# Generated by Django 6.1 on 2026-08-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_rules_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='client_ref',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='origin',
            field=models.CharField(choices=[('server', 'server'), ('offline', 'offline')], db_index=True, default='server', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('client_ref', ''), _negated=True), fields=('player', 'client_ref'), name='unique_client_ref_per_player'),
        ),
    ]
