# Generated by Django 6.1 on 2026-08-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.PositiveIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('online', 'Online'), ('post_match', 'Post-match'), ('self_play', 'Self-play')], default='post_match', max_length=16)),
                ('games', models.PositiveIntegerField(default=0)),
                ('transitions', models.PositiveIntegerField(default=0)),
                ('loss', models.FloatField(default=0.0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RLPolicyWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(db_index=True, unique=True)),
                ('model_blob', models.BinaryField(blank=True, default=b'')),
                ('games_trained', models.PositiveIntegerField(default=0)),
                ('last_loss', models.FloatField(blank=True, null=True)),
                ('elo_rating', models.IntegerField(default=1200)),
                ('architecture', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-version',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='ai_only_one_active_policy')],
            },
        ),
        migrations.CreateModel(
            name='AIMoveMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField(default=0)),
                ('state_fen', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('chosen_move', models.CharField(db_index=True, max_length=64)),
                ('ollama_reasoning', models.TextField(blank=True, default='')),
                ('reasoning_source', models.CharField(blank=True, default='heuristic', max_length=16)),
                ('reward_score', models.FloatField(default=0.0)),
                ('q_value', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('was_repeat_mistake', models.BooleanField(db_index=True, default=False)),
                ('considered_moves', models.JSONField(blank=True, default=list)),
                ('policy_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to='game.match')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_memories', to='game.gamestate')),
            ],
            options={
                'ordering': ('match_id', 'turn_number', 'id'),
                'indexes': [models.Index(fields=['state_fen', 'chosen_move'], name='ai_aimoveme_state_f_a070d2_idx')],
            },
        ),
    ]
